name: weixin
on:
  workflow_dispatch:
  schedule: 
    # UTC 0:00 -> 北京时间 8:00
    - cron: '0 0 * * *'
jobs:
#将工作流程中运行的所有作业组合在一起
  build:
  #定义名为 build 的作业。 子键将定义作业的属性 
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2
    
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Set timezone
        run: |
          sudo cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
      - name: install pip packages
        run: |
          python -m pip install --upgrade pip
          pip3 install -r requirements.txt
      - name: weixin
        run: |
          echo "开始执行主程序..."
          python3 -V  # 输出 Python 版本
          python3 main.py
        env:  # 添加环境变量用于调试
          PYTHONUNBUFFERED: 1
